name: pd-build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest] #, macos-14, macos-13

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup C/C++ Compiler
      if: matrix.os == 'windows-latest'
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: clang-latest
    
    - name: Verify GCC Installation
      run: |
        clang --version
        clang++ --version

    - name: Get puredata source code
      run: git clone https://github.com/pure-data/pure-data.git ${{github.workspace}}/puredata
  
# for windows we have to explicitly add the libsamplerate build job here
    - name: build_libsamplerate_win
      run: |
        cd libsamplerate
        mkdir -p build && cd build && cmake -DLIBSAMPLERATE_EXAMPLES=OFF -DBUILD_TESTING=OFF ..
        cmake --build . --config 'Release'
        
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/rtneural_pd/build

# Build the plugins

    - name: Configure CMake (Unix)
      shell: bash
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/rtneural_pd/build
      run: cmake .. -DCMAKE_BUILD_TYPE='Release' -DPD_PATH=${{github.workspace}}/puredata/src

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      working-directory: ${{github.workspace}}\rtneural_pd\build
      run: cmake .. -DCMAKE_BUILD_TYPE='Release' -DPD_PATH=${{github.workspace}}\puredata\src

    - name: Build (Unix)
      if: matrix.os != 'windows-latest'
      working-directory: ${{github.workspace}}/rtneural_pd/build
      shell: bash
      run: cmake --build . --config "Release" --target install

    - name: Build (Windows)
      working-directory: ${{github.workspace}}\rtneural_pd\build
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: cmake --build . --config "Release" --target install

# Zip the pd plugins

    - name: Zip up build (macOS-14)
      if: matrix.os == 'macos-14'
      shell: bash
      working-directory: ${{github.workspace}}/rtneural_pd/build
      run: zip -r rtneural_pd-mac_arm.zip rtneural_pd

    - name: Zip up build (macOS-13)
      if: matrix.os == 'macos-13'
      shell: bash
      working-directory: ${{github.workspace}}/rtneural_pd/build
      run: zip -r rtneural_pd-mac_intel.zip rtneural_pd 

    - name: Zip up build (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      working-directory: ${{github.workspace}}\rtneural_pd\build\rtneural_pd
      run: Compress-Archive -Path ${{github.workspace}}\rtneural_pd\build\rtneural_pd -Destination "${{github.workspace}}/rtneural_pd-${{runner.os}}.zip"

# Zip the python folder

    - name: Zip up python
      if: matrix.os == 'macOS-14'
      shell: bash
      working-directory: ${{github.workspace}}
      run: zip -r RTNeural_python.zip RTNeural_python 

  # upload pd binaries to release

    - name: Check if release has been created
      uses: mukunku/tag-exists-action@v1.6.0
      id: checkTag
      with:
        tag: 'v1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release (macOS-14)
      if: steps.checkTag.outputs.exists == false && matrix.os == 'macos-14'
      id: create_release_arm
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: rtneural_pd-arm-${{ github.ref }}
        draft: false
        prerelease: false

    - name: Create Release (macOS-13)
      if: steps.checkTag.outputs.exists == false && matrix.os == 'macos-13'
      id: create_release_x86
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: rtneural_pd-x86-${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries to release (macOS-14)
      if: matrix.os == 'macos-14'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/rtneural_pd/build/rtneural_pd-mac_arm.zip
        asset_name: rtneural_pd-mac_arm.zip
        tag: ${{ github.ref }}

    - name: Upload binaries to release (macOS-13)
      if: matrix.os == 'macos-13'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/rtneural_pd/build/rtneural_pd-mac_intel.zip
        asset_name: rtneural_pd-mac_intel.zip
        tag: ${{ github.ref }}

    - name: Upload binaries to release (Windows)
      if: matrix.os == 'windows-latest'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/rtneural_pd-${{runner.os}}.zip
        asset_name: rtneural_pd-${{runner.os}}.zip
        tag: ${{ github.ref }}

# upload python files to release
  
    - name: Upload binaries to release (python)
      if: matrix.os == 'macOS-14'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/RTNeural_python.zip
        asset_name: RTNeural_python.zip
        tag: ${{ github.ref }}
